services:
  nginx:
    ports:
      - ${NGINX_HOST_IP}:${NGINX_HOST_PORT}:80
    volumes:
      - ./../:/var/www/html:cached
  php-fpm:
    depends_on:
      - redis
      - postgres
    links:
      - redis
      - postgres
    volumes:
      - ./../:/var/www/html:cached
  supervisor:
    depends_on:
      - redis
      - postgres
    links:
      - redis
      - postgres
    volumes:
      - ./../:/var/www/html:cached
  postgres:
    build:
      context: ./postgres
      args:
        - POSTGRES_VERSION=14-alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_HOST_IP}:${POSTGRES_HOST_PORT}:5432
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - local
volumes:
  postgres:
