services:
    platform:
        build:
            context: ./platform
            args:
                - TZ=${TIMEZONE}
                - INSTALL_BCMATH=false
                - INSTALL_PHPREDIS=true
                - INSTALL_OPCACHE=true
                - INSTALL_IMAGEMAGICK=false
                - INSTALL_EXIF=false
                - INSTALL_PCNTL=true
                - INSTALL_INTL=false
                - INSTALL_SOAP=false
                - INSTALL_PGSQL=true
                - INSTALL_MYSQL=true
                - INSTALL_GETTEXT=false
                - INSTALL_SOCKETS=false
                - INSTALL_MEMCACHED=false
                - INSTALL_PECL_SYNC=false
                - INSTALL_PECL_MONGODB=false
                - OPENSSL_ENABLE_GOST_SUPPORT=false
        profiles:
            - install
    app:
        build:
            context: './../'
            dockerfile: ./docker/app/Dockerfile
            args:
                - PLATFORM_CONTAINER_NAME=${COMPOSE_PROJECT_NAME}${CONTAINER_NAME_DELIMITER}platform:latest
        profiles:
            - install
        depends_on:
            - platform
    php-fpm:
        build:
            context: ./php-fpm
            args:
                - APP_CONTAINER_NAME=${COMPOSE_PROJECT_NAME}${CONTAINER_NAME_DELIMITER}app:latest
        depends_on:
            - redis
        links:
            - redis
        extra_hosts:
            - "host.docker.internal:host-gateway"
        networks:
            - local
    nginx:
        build:
            context: ./nginx
            args:
                - TZ=${TIMEZONE}
                - APP_CONTAINER_NAME=${COMPOSE_PROJECT_NAME}${CONTAINER_NAME_DELIMITER}app:latest
        depends_on:
            - php-fpm
        links:
            - php-fpm
        networks:
            - local
    supervisor:
        build:
            context: ./supervisor
            args:
                - APP_CONTAINER_NAME=${COMPOSE_PROJECT_NAME}${CONTAINER_NAME_DELIMITER}app:latest
                - PLATFORM_CONTAINER_NAME=${COMPOSE_PROJECT_NAME}${CONTAINER_NAME_DELIMITER}platform:latest
        depends_on:
            - redis
        links:
            - redis
        extra_hosts:
            - "host.docker.internal:host-gateway"
        networks:
            - local
    redis:
        image: redis:latest
        volumes:
            - redis:/data
        networks:
            - local
networks:
    local:
        driver: bridge
volumes:
    redis:
