version: '2'
services:
  platform:
    labels:
      - traefik.enable=false
  app:
    labels:
      - traefik.enable=false
  php-cli:
    labels:
      - traefik.enable=false
    volumes:
      - laravel-app:/var/www/html/storage/app
      - laravel-log:/var/www/html/storage/logs
  php-fpm:
    restart: always
    labels:
      - traefik.enable=false
    volumes:
      - laravel-app:/var/www/html/storage/app
      - laravel-log:/var/www/html/storage/logs
  nginx:
    restart: always
    labels:
      - traefik.enable=true
      - traefik.domain=${NGINX_TRAEFIK_DOMAIN}
      - traefik.backend=${COMPOSE_PROJECT_NAME}-nginx
      - traefik.docker.network=webproxy
      - traefik.frontend.entryPoints=${NGINX_TRAEFIK_FRONTEND_ENTRY_POINTS}
      - traefik.port=80
      - traefik.frontend.rule=Host:${NGINX_TRAEFIK_DOMAIN}
      - traefik.frontend.headers.SSLRedirect=${NGINX_TREFIK_SSL_REDIRECT}
      - traefik.frontend.headers.SSLHost=${NGINX_TRAEFIK_DOMAIN}
      - traefik.frontend.headers.SSLForceHost=${NGINX_TRAEFIK_FORCE_SSL}
      - traefik.weight=${NGINX_TRAEFIK_WEIGHT}
    networks:
      - webproxy
  supervisor:
    restart: always
    labels:
      - traefik.enable=false
    volumes:
      - laravel-app:/var/www/html/storage/app
      - laravel-log:/var/www/html/storage/logs
  postgres:
    restart: always
    labels:
      - traefik.enable=false
  redis:
    restart: always
    labels:
      - traefik.enable=false
  memcached:
    restart: always
    labels:
      - traefik.enable=false
  minio:
    restart: always
    ports:
      - ${MINIO_CONSOLE_HOST_IP}:${MINIO_CONSOLE_HOST_PORT}:9001
    labels:
      - traefik.enable=true
      - traefik.domain=${MINIO_TRAEFIK_DOMAIN}
      - traefik.backend=${COMPOSE_PROJECT_NAME}-minio
      - traefik.docker.network=webproxy
      - traefik.frontend.entryPoints=${MINIO_TRAEFIK_FRONTEND_ENTRY_POINTS}
      - traefik.port=9000
      - traefik.frontend.rule=Host:${MINIO_TRAEFIK_DOMAIN}
      - traefik.frontend.headers.SSLRedirect=${MINIO_TREFIK_SSL_REDIRECT}
      - traefik.frontend.headers.SSLHost=${MINIO_TRAEFIK_DOMAIN}
      - traefik.frontend.headers.SSLForceHost=${MINIO_TRAEFIK_FORCE_SSL}
      - traefik.weight=${MINIO_TRAEFIK_WEIGHT}
    networks:
      - local
      - webproxy
  imaginary:
    restart: always
    labels:
      - traefik.enable=true
      - traefik.domain=${IMAGINARY_TRAEFIK_DOMAIN}
      - traefik.backend=${COMPOSE_PROJECT_NAME}-imaginary
      - traefik.docker.network=webproxy
      - traefik.frontend.entryPoints=${IMAGINARY_TRAEFIK_FRONTEND_ENTRY_POINTS}
      - traefik.port=9000
      - traefik.frontend.rule=Host:${IMAGINARY_TRAEFIK_DOMAIN}
      - traefik.frontend.headers.SSLRedirect=${IMAGINARY_TREFIK_SSL_REDIRECT}
      - traefik.frontend.headers.SSLHost=${IMAGINARY_TRAEFIK_DOMAIN}
      - traefik.frontend.headers.SSLForceHost=${IMAGINARY_TRAEFIK_FORCE_SSL}
      - traefik.weight=${IMAGINARY_TRAEFIK_WEIGHT}
    networks:
      - local
      - webproxy
volumes:
  laravel-app:
  laravel-log:
networks:
  webproxy:
    external: true
